#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2014 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }

[ -n "OZH_REQUIRE" ] && {

  _filter_eztv(){ html2text -width 10000 | grep -oP '[-_A-Za-z0-9()\[\]]+' | grep '_' | grep -v 'comment' | tail -n 53 | head -n 50; }

  eztv(){
    local url="http://eztv.it"
    wget -q "$url" -O- | _filter_eztv; }; }

[ -n "FEED_REQUIRE" ] && {

  _feed_eztv(){
    local url="http://eztv.it"
    count=1; data="$(cat $task/cache | _filter_rss)"
    echo "$data" > $task/new
    [ "$(cat $task/new)" = "$(cat $task/cur)" ] || {
      echo "$data" > $task/cur
    DISPLAY=:0 notify-send -u critical "eztv" "$data"; }; }

  _install_feed_eztv(){
    local url="http://eztv.it"
    local p="$OZH/feed/list/eztv"; mkdir -p "$p"; echo "$url" > "$p/url"; echo '. $OZH/feed/eztv; _feed_eztv' > "$p/onupdate"; }; }
