#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2014 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }


[ -n "OZH_REQUIRE" ] && {
  _feed_eztv_filter(){ sed -n '/<title/{s/.*CDATA\[//;s/\]\]>.*//;s/\[.*//;p}' | sed '1,2d'; }
  _feed_eztv_format(){ awk '{s=""}/ [0-9]*x[0-9]*/{s=$NF;$NF=""}{printf "'$bred$white$bold' %s '$R' %s\n",$0,s}'; }
  _feed_eztv_defaults(){ url="http://ezrss.it/feed/"; }
  eztv(){ _feed_eztv_defaults; wget -qO- "$url" | _feed_eztv_filter | _feed_eztv_format; }; }

[ -n "FEED_REQUIRE" ] && {
  _feed_eztv(){ count=1; format=_feed_eztv_filter; }; }
