#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2014 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }


_filter_rss(){ grep -P '<title>.*?</title>' | busybox sed 's/<title>//gi;s/<\/title>//gi' | head -n5 | tail -n4; }

[ -n "OZH_REQUIRE" ] && {

  heise(){
    local url="http://www.heise.de/newsticker/heise-atom.xml"
    wget -O- "$url" | _filter_rss; }; }

[ -n "FEED_REQUIRE" ] && {

  _feed_heise(){
    count=1; data="$(cat $task/cache | _filter_rss)"
    echo "$data" > $task/new
    [ "$(cat $task/new)" = "$(cat $task/cur)" ] || {
      echo "$data" > $task/cur
    DISPLAY=:0 notify-send -u critical "heise" "$data"; }; }

  _install_feed_heise(){
    local url="http://www.heise.de/newsticker/heise-atom.xml"
    local p="$OZH/feed/list/heise"; mkdir -p "$p"; echo "$url" > "$p/url"; echo '. $OZH/feed/heise; _feed_heise' > "$p/onupdate"; }; }
